name: CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Step 3: Install system dependencies (fallback for distutils)
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libjpeg-dev zlib1g-dev libpng-dev libfreetype6-dev rustc libpython3.12-stdlib || true

    # Step 4: Ensure distutils is installed
    - name: Ensure distutils is Installed
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade setuptools

    # Step 5: Upgrade pip, setuptools, and wheel
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    # Step 6: Pre-Install Problematic Libraries
    - name: Pre-Install Specific Libraries
      run: |
        pip install --no-cache-dir Pillow
        pip install --no-cache-dir tokenizers

    # Step 7: Install dependencies from requirements.txt
    - name: Install Dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt --verbose

    # Step 8: Verify Installed Packages
    - name: Verify Installed Packages
      run: pip list

    # Step 9: Run Application (if applicable)
    - name: Run App
      run: |
        streamlit run app.py  # Replace with your app's entry point
