name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Clear pip cache
      run: pip cache purge

    - name: Uninstall old versions
      run: |
        pip uninstall torch torchvision torchaudio -y || true

    - name: Install Dependencies
      run: pip install -r requirements.txt --no-cache-dir

    - name: Verify Installed Packages
      run: |
        pip list
        python -c "import torch; print(torch.__version__)"
        python -c "import torchvision; print(torchvision.__version__)"
        python -c "import torchaudio; print(torchaudio.__version__)"
