name: CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Step 3: Upgrade pip
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    # Step 4: Install system dependencies
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libjpeg-dev zlib1g-dev libpng-dev libfreetype6-dev rustc

    # Step 5: Pre-Install Specific Libraries
    - name: Pre-Install Specific Libraries
      run: |
        pip install --no-cache-dir Pillow
        pip install --no-cache-dir tokenizers

    # Step 6: Install dependencies from requirements.txt
    - name: Install Dependencies
      run: pip install --no-cache-dir -r requirements.txt

    # Step 7: Verify Installed Packages
    - name: Verify Installed Packages
      run: pip list

    # Step 8: Run Application (Adjust as needed)
    - name: Run App
      run: |
        streamlit run app.py  # Replace "app.py" with your actual entry point
