name: CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Step 3: Install system dependencies
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev zlib1g-dev libpng-dev libfreetype6-dev rustc build-essential

    # Step 4: Upgrade pip, setuptools, and wheel
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    # Step 5: Clear pip cache
    - name: Clear pip cache
      run: pip cache purge

    # Step 6: Install Python dependencies
    - name: Install Dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt

    # Step 7: Patch Incompatible Libraries
    - name: Fix Compatibility Issues
      run: |
        pip install importlib-metadata==6.8.0  # Avoid pkg_resources issues with pkgutil
        pip install -U pkg_resources

    # Step 8: Verify Installed Packages
    - name: Verify Installed Packages
      run: |
        pip list

    # Step 9: Run Tests (if applicable, adjust the command to your project)
    - name: Run Tests
      run: |
        pytest tests/  # Replace with your test command or folder

    # Step 10: Cleanup (optional)
    - name: Cleanup
      run: |
        sudo apt-get clean
