name: Python Application Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Upgrade pip and Set Configuration
      run: |
        python -m pip install --upgrade pip
        pip config set global.verbose true

    - name: Clear pip cache
      run: |
        pip cache purge

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Check Installed Packages
      run: |
        pip list

    - name: Run Tests (optional)
      run: |
        echo "Run your tests here"

    - name: Additional Debug Info (optional)
      run: |
        pip debug --verbose
