name: CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Step 3: Install system dependencies (fix distutils issue)
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libjpeg-dev zlib1g-dev libpng-dev libfreetype6-dev rustc python3.12-venv

    # Step 4: Ensure pip, setuptools, wheel, and distutils
    - name: Ensure pip, setuptools, and wheel
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip setuptools wheel

    # Step 5: Install dependencies from requirements.txt
    - name: Install Dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt --verbose

    # Step 6: Verify Installed Packages
    - name: Verify Installed Packages
      run: pip list

    # Step 7: Run Application (if applicable)
    - name: Run App
      run: |
        streamlit run app.py  # Replace with your app's entry point
